/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/hero.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const HeroModel = (props) => {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/hero.glb");
	// const { actions } = useAnimations(animations, group);

	// console.log(names);

	// useEffect(() => {
	// 	actions[names[0]].reset().fadeIn(0.5).play();
	// }, []);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group
					name="body001"
					position={[0, -0.038, 0]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.011}
				>
					<mesh
						name="Mesh002"
						geometry={nodes.Mesh002.geometry}
						material={materials["Material #15.002"]}
					/>
					<mesh
						name="Mesh002_1"
						geometry={nodes.Mesh002_1.geometry}
						material={materials["Material #47.002"]}
					/>
					<mesh
						name="Mesh002_2"
						geometry={nodes.Mesh002_2.geometry}
						material={materials["Material #29.002"]}
					/>
					<mesh
						name="Mesh002_3"
						geometry={nodes.Mesh002_3.geometry}
						material={materials["Material #16.002"]}
					/>
					<mesh
						name="Mesh002_4"
						geometry={nodes.Mesh002_4.geometry}
						material={materials["Material #17.002"]}
					/>
					<mesh
						name="Mesh002_5"
						geometry={nodes.Mesh002_5.geometry}
						material={materials["Material #41.002"]}
					/>
					<mesh
						name="Mesh002_6"
						geometry={nodes.Mesh002_6.geometry}
						material={materials["Material #44.002"]}
					/>
					<mesh
						name="Mesh002_7"
						geometry={nodes.Mesh002_7.geometry}
						material={materials["Material #60.002"]}
					/>
				</group>
			</group>
		</group>
	);
};

export default HeroModel;

useGLTF.preload("/models/hero.glb");
